POST https://ngoaingu24h.vn/get-documents-by-course-id
# POST https://ngoaingu24h.vn/get-path-by-id
# POST https://ngoaingu24h.vn/get-user-exam-info
# POST https://ngoaingu24h.vn/get-topic-child-by-ids
# content-length: 43
content-type: application/x-www-form-urlencoded; charset=UTF-8
# cookie: JSESSIONID=0cB7Nfjo_hRRZrpgpAHN1g; koolsoft-loxo-web--session-id--local=0cB7Nfjo_hRRZrpgpAHN1g; show_fisrt_access_website=true

courseId=5671445459894272&offset=0&limit=9999
# courseId=5958158015004672&topicId=5590995047546880&pathIds%5B%5D=-1
# courseId=5820662448914432&userId=1142157472876776
# courseId=5958158015004672&parentId=5590995047546880&userId=tackecon